
interface IPhoneStoryFooterProps {
  homeGoals: any[];
  awayGoals: any[];
  cards: any[];
  timelineEvents: any[];
  homeTeamColor: string;
  awayTeamColor: string;
  fixture: any;
}

const IPhoneStoryFooter = ({
  homeGoals,
  awayGoals,
  cards,
  timelineEvents,
  homeTeamColor,
  awayTeamColor,
  fixture
}: IPhoneStoryFooterProps) => {
  return (
    <div className="mt-auto">
      {/* Statistics Section */}
      <div className="px-4 py-3 bg-gradient-to-r from-slate-50 via-slate-100 to-slate-50 border-t-2 border-slate-200">
        <div className="grid grid-cols-3 gap-3 text-center">
          <div>
            <div className="font-bold text-lg mb-0.5" style={{ color: homeTeamColor }}>
              {homeGoals.length}
            </div>
            <div className="text-muted-foreground text-xs font-semibold mb-0.5">Goals</div>
            <div className="text-xs text-muted-foreground">
              <div className="break-words max-w-[65px] mx-auto leading-tight font-medium">
                {fixture.home_team?.name || 'Home'}
              </div>
            </div>
          </div>
          <div>
            <div className="font-bold text-lg mb-0.5 text-amber-600">{cards.length}</div>
            <div className="text-muted-foreground text-xs font-semibold mb-0.5">Cards</div>
            <div className="text-xs text-muted-foreground font-medium">
              {timelineEvents.length} Events
            </div>
          </div>
          <div>
            <div className="font-bold text-lg mb-0.5" style={{ color: awayTeamColor }}>
              {awayGoals.length}
            </div>
            <div className="text-muted-foreground text-xs font-semibold mb-0.5">Goals</div>
            <div className="text-xs text-muted-foreground">
              <div className="break-words max-w-[65px] mx-auto leading-tight font-medium">
                {fixture.away_team?.name || 'Away'}
              </div>
            </div>
          </div>
        </div>
      </div>
      
      {/* Branding Footer */}
      <div className="px-4 py-2.5 bg-gradient-to-r from-slate-100 via-slate-50 to-slate-100">
        <div className="text-center">
          <div className="text-sm font-bold text-slate-700 mb-0.5 leading-tight">
            📊 Match Summary Report
          </div>
          <div className="text-xs text-slate-500 font-medium leading-tight">
            Generated by Referee Tools • {new Date().toLocaleDateString()}
          </div>
        </div>
      </div>
    </div>
  );
};

export default IPhoneStoryFooter;
