
const MobileExportFooter = () => {
  return (
    <div className="mt-auto p-4 bg-gradient-to-r from-slate-100 via-slate-50 to-slate-100 border-t-2 border-slate-200">
      <div className="text-center">
        <div className="text-sm font-bold text-slate-700 mb-1">
          📊 Match Summary Report
        </div>
        <div className="text-xs text-slate-500">
          Generated by Referee Tools • {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
};

export default MobileExportFooter;
