// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvtizejqfbeihsqkbxul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2dGl6ZWpxZmJlaWhzcWtieHVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NDkwMTgsImV4cCI6MjA2NDMyNTAxOH0.5Qmk3LrLjPZVazeeM4sZq283AVbSn_kdq2wuEvEEH5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);